// <auto-generated />
namespace TrackTime.Core.Migrations

open System
open FirebirdSql.EntityFrameworkCore.Firebird.Metadata
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open TrackTime

[<DbContext(typeof<AppDataLiteDb.MyAppDataContext>)>]
type MyAppDataContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
            .HasAnnotation("Relational:MaxIdentifierLength", 31)
            .HasAnnotation("ProductVersion", "5.0.12")
            |> ignore

        modelBuilder.Entity("TrackTime.DataModels+Customer", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("BIGINT") |> ignore
            b.Property<int>("CustomerState")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string option>("Email")
                .IsRequired(false)
                .HasMaxLength(100)
                .HasColumnType("VARCHAR(100)") |> ignore
            b.Property<string>("Name")
                .IsRequired(false)
                .HasMaxLength(50)
                .HasColumnType("VARCHAR(50)") |> ignore
            b.Property<string>("Notes")
                .IsRequired(false)
                .HasColumnType("BLOB SUB_TYPE TEXT") |> ignore
            b.Property<string option>("Phone")
                .IsRequired(false)
                .HasMaxLength(20)
                .HasColumnType("VARCHAR(20)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Customers") |> ignore

        )) |> ignore

        modelBuilder.Entity("TrackTime.DataModels+TimeEntry", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("BIGINT") |> ignore
            b.Property<bool>("BeenBilled")
                .IsRequired(true)
                .HasColumnType("BOOLEAN") |> ignore
            b.Property<string>("Description")
                .IsRequired(false)
                .HasColumnType("BLOB SUB_TYPE TEXT") |> ignore
            b.Property<string>("Notes")
                .IsRequired(false)
                .HasColumnType("BLOB SUB_TYPE TEXT") |> ignore
            b.Property<DateTime option>("TimeEnd")
                .IsRequired(false)
                .HasColumnType("TIMESTAMP") |> ignore
            b.Property<DateTime>("TimeStart")
                .IsRequired(true)
                .HasColumnType("TIMESTAMP") |> ignore
            b.Property<Int64>("WorkItemId")
                .IsRequired(true)
                .HasColumnType("BIGINT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("TimeEntries") |> ignore

        )) |> ignore

        modelBuilder.Entity("TrackTime.DataModels+WorkItem", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("BIGINT") |> ignore
            b.Property<bool>("BeenBilled")
                .IsRequired(true)
                .HasColumnType("BOOLEAN") |> ignore
            b.Property<string option>("Body")
                .IsRequired(false)
                .HasColumnType("BLOB SUB_TYPE TEXT") |> ignore
            b.Property<Int64>("CustomerId")
                .IsRequired(true)
                .HasColumnType("BIGINT") |> ignore
            b.Property<DateTime>("DateCreated")
                .IsRequired(true)
                .HasColumnType("TIMESTAMP") |> ignore
            b.Property<string option>("Description")
                .IsRequired(false)
                .HasMaxLength(100)
                .HasColumnType("VARCHAR(100)") |> ignore
            b.Property<DateTime>("DueDate")
                .IsRequired(true)
                .HasColumnType("TIMESTAMP") |> ignore
            b.Property<bool>("IsBillable")
                .IsRequired(true)
                .HasColumnType("BOOLEAN") |> ignore
            b.Property<bool>("IsCompleted")
                .IsRequired(true)
                .HasColumnType("BOOLEAN") |> ignore
            b.Property<bool>("IsFixedPrice")
                .IsRequired(true)
                .HasColumnType("BOOLEAN") |> ignore
            b.Property<string>("Title")
                .IsRequired(false)
                .HasMaxLength(50)
                .HasColumnType("VARCHAR(50)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("WorkItems") |> ignore

        )) |> ignore

